# src/config.py

# Default (Light Mode) Color Scheme Definitions
COLOR_PRIMARY = "#640D5F"
COLOR_SECONDARY = "#D91656"
COLOR_ACCENT = "#EB5B00"
COLOR_BACKGROUND = "#FFB200"
COLOR_TEXT = "#FFFFFF"

# Dark Mode Color Scheme
DARK_COLOR_PRIMARY = "#DCDCDD"
DARK_COLOR_SECONDARY = "#C5C3C6"
DARK_COLOR_ACCENT = "#46494C"
DARK_COLOR_BACKGROUND = "#4C5C68"
DARK_COLOR_TEXT = "#1985A1"
